realityhandbook [
    date: 26-Sep-2007/1:27+3:00
    category: 'essay
    title: "Consciousness and The Invisible Wire"
    slug: %consciousness-and-the-invisible-wire
    tags: []
    old: http://realityhandbook.livejournal.com/45719.html
]
[{When studying the work of people who focus on neurons and the brain to find consciousness, I'm quite interested. I read <a href="http://en.wikipedia.org/wiki/Consciousness_Explained">Consciousness Explained</a> by Daniel Dennett, though I like the more open-minded attitude that <a href="http://en.wikipedia.org/wiki/Oliver_Sacks">Oliver Sacks</a> has in describing people with abnormal brain circumstances. Dennett really seeks to squash the notion that there are things about the brain we don't understand...I think he's loony for pushing that viewpoint.}]
[{Putting too much on the brain seems parallel with a turn-of-the-century scientist studying a modern computer on a wireless network. Knowing what he does about electrical conductivity, he might trace the internal circuits and start mapping out the machine. As he delves, he'll discover the entire field of semiconductor science; marveling at how tiny things get and the millions of transistors he finds when he breaks the chip apart. In fact, he can be so overwhelmed by the intricate and magical beauty of this new field that he might ridicule those who invoke "invisible magic wires" to explain what's going on: can't they see how much of what they had not understood before is explained by the architecture he's discovered? Don't they see how information is stored magnetically on the hard drive, and migrated into physical memory on the bus? Not a single invisible wire need be invoked to explain the entire operation of <a href="http://en.wikipedia.org/wiki/The_Sims">The Sims</a>.}]
[{Yet for all his amazing findings, his assumption is wrong: there *are* invisible magic wires...he's merely yet to discover the 802.11g technology integrated into the Centrino chip and exactly what role it plays in the overall system. Precisely how much his explanation fails depends on what programs he runs--if he sticks to spreadsheets and Solitaire, then the invisible magic wire won't be relevant at all. But if he happens to run a web browser, then questions his model can't answer start to mount up.}]
[{People like Dennett, Dawkins, and the neuroscience camp are doing a great job of characterizing systems in the brain. But their insistence that the brain is where the buck stops is parallel to telling people who are getting IM messages or streaming video that it's all coming from their hard drive. I'm not in a position to show them The Invisible Wire any better than Galileo could have handed anyone a moon rock--I'm just a guy who's turned off by how little credit they give to the experiences of intelligent people who just happen to have their firewall configured differently.}]
[{Maybe this invisible wire lives somewhere in <a href="http://www.tenthdimension.com/medialinks.php">The Tenth Dimension</a>?}]
