realityhandbook [
    date: 6-Jun-2008/7:43+3:00
    category: 'lucid-dream
    title: "Kanye's Golden Collapsible Cane"
    slug: %kanyes-golden-collapsible-cane
    tags: [cane loggers neutral technology]
    old: http://realityhandbook.livejournal.com/83730.html
]
[{At first I had the feeling that I was entering some kind of exclusive music club. In my hands was a golden collapsible cane, and somehow I knew that I needed to return this object to someone there who had high status.}]
[note {Another collapsible cane--though not a golden one--appeared in this dream <a href="http://realityhandbook.org/lucid-dream/amazing-feats-of-the-mind-people/">when my car turned into a cane</a>.}]
[{A man with a clipboard was making sure that everyone was on the list, and I felt out of place overwhelmed. However, I was allowed through without being checked...and guided into a meeting where everyone seemed to accept my being there.}]
[{There was some technical presentation and I was taking notes. After the presentation, people formed a line on either side of me. I went to walk down the line and out of the room, but was stopped by someone.}]
[man: {You need to introduce yourself to everyone. All the people here are directors.}]
[note {At the time I thought this meant "movie director", but perhaps "division manager" would make more sense.}]
[{I walked down the line, casually shaking hands. People would tell me their names and what they were responsible for, all of it had to do with software development projects. At one point, I met a man with several boxes of software on a table in front of him. He said he'd been working on many projects for a long time, and introduced himself as a 'logger'.}]
[note {'Loggers' first appeared in a dream in which I <a href="http://realityhandbook.org/lucid-dream/genital-plus-one-and-pillows-zero-zero/">perceived them as a 'bad thing'</a>.}]
[{Recognizing the term as one of interest from my dreams, I stopped and inquired further, though I did not become completely lucid.}]
[me: {I'm curious...what does a logger <i>do</i>? Is this related to tracking bugs and correlating them with causative factors?}]
[logger: {Ummm, no, not really. Let me show you some of the things I do.}]
[{He showed me pages of line graphs and tried to explain what they meant. I didn't really understand it, and couldn't read the labels on the axes. So I persisted in believing that it had something to do with bug tracking, and decided to make haste and leave the room.}]
[{Still holding the golden cane in my hand, and I went to a bouncer who was at a door. There were lists being checked and things of that nature, but I didn't want to deal with worrying about whether I was on the list or not in order to see the boss in person. So I just handed the cane over.}]
[me: "This is for Kanye."]
[note {For some reason, when I said this, I thought I was bringing the object to rapper <a href="http://en.wikipedia.org/wiki/Kanye_West">Kanye West</a>...none of whose music I've heard. But I know of no one else named Kanye. Also, it was a <i>cane</i> that I was returning, so this could be a crossed mental wire of some sort.}]
[{The bouncer looked menacingly at me, and took the cane and thrashed it up against the wall. I was baffled and stepped back.}]
[me: {That was a bad idea. It wasn't a random gift from an admirer that you can just destroy. The meaning you should have taken was, 'I am returning this, it belongs to Kanye'.}]
[{There was a look of fear in the bouncer's eyes. A woman who looked a bit like Whoopi Goldberg stepped out of the room being guarded. She looked at the battered cane on the ground, looked at me, and looked at the bouncer.}]
[me: {I'm sorry, I just told him to give it to you. It was late and I didn't want trouble with procedures for granting an audience.}]
[kanye-west: ("to bouncer") {You were hired to keep people from getting in and messing with me or my stuff...not to <i>break my stuff</i>. You're fired!}]
[bouncer: ("whining") {Come on! You'd think that donut I got for you would count for something.}]
[kanye-west: "What? No! Get out of here now."]
[{The bouncer left, and kanye west shook her head and faced me. I was really stressed out by this point.}]
[kanye-west: {Unbelievable. I'm not saying it wasn't a good donut. It was from that new place downtown...really fresh, I've liked everything I've had from them so far. Have you been there yet?}]
[me: ("nervous") "Uhh...no."]
[kanye-west: {Well anyway, you don't have to worry about that guy anymore, he's history. Now why don't you come in and tell me about the meeting?}]
[{Despite feeling it was too late, I followed along into the office. kanye west had a piece of paper representing a seating chart of the room I had been in. She presented to me so I could point to which person had said what.}]
[kanye-west: {How was everyone's hair? Probably awful, were they wearing hats?}]
[me: {I'm afraid that if you're going to want details on what specific people said, I'm going to have to go get my notes. I really hadn't planned on meeting you about this right now.}]
[kanye-west: "That's fine, go get them. I'll wait."]
[{I went to get my notes, that I sensed I had left in the meeting room. But somehow I ended up fumbling around in the trunks of cars and woke up.}]
