realityhandbook [
    date: 2-Jun-2010/9:56+3:00
    category: 'lucid-dream
    title: "Low Budget Iron Man"
    slug: %low-budget-iron-man
    tags: [neutral matrix conspiracy]
]
["I was speaking to a dolphin in a dream."]
[dolphin: {I just managed to find another way around, to a different stream; there was a connection they didn't know about; I can find out about the blogs there. I think we're getting very close to putting this one together.}]
[me: "I'll believe it when I see it. But good luck."]
[{My point of view shifted to where some people were walking up the street to a house that I perceived to be like my grandmother's. I intercepted them. There was an older woman and an older man; I recognized the woman for some reason. The older man handed me a pair of goldish earrings.}]
[man: {We got these back for you. Your grandmother was always giving these things away...or selling nice necklaces for $2 when they were worth much more.}]
[{Flipping the earrings over I noticed that on the other side of the pin, the part that would clasp behind the ear, the formation was a hemispherical black bead. I felt a moment of realization.}]
[me: ("thinking") {A-ha! We didn't think they had access to any parts like this, but that how they made it look like a creature with eyes.}]
[{Somewhat later I was on the set of the filming of what looked like an extremely low-budget Iron Man movie. It had multiple Iron Man outfits. There was some sort of explosion that was unplanned.}]
[me: "What just happened?"]
[iron-man: "Our unscrupulous enemies strike again."]
[me: {Well I hope you were rolling camera, because that explosion was better than your suit.}]
[{The people were gathered around a camera to watch a TV about terrorists who had detonated explosives and were blowing up cities. I saw some buildings in Seattle falling down. People were panicking, and I was upset at first but then I looked closer at the images.}]
[me: {Those aren't real detonations, the patterns are artificial. It's a bad special effect - a computer graphic.}]
["The crowd looked at me."]
[me: {Look, when I wake up...those buildings will still be there. That's not to say your lives here aren't 'real'...it's just easier to pull that crap on people who are perception-locked into this zone.}]
["A woman stepped in with a statement."]
[woman: {He doesn't mean real detonations like that aren't possible.}]
[me: {Oh certainly, it could happen. But doing it in a deeply-structured space would just involve a lot more planning, effort, and materials. My point is just that unless you're a cartoon character, you don't need to be afraid of pencil erasers. A digital collapsing effect on a 3D model of a city is basically just erasing a picture.}]
["The woman and I began going up some escalators."]
[me: {Remember the conditions that make it possible to do this. It's like the Truman show. High control of access points...most of which will be shut down. It's like places you can only get to when you go through controlled spaces--elevators, air routes. And of course since they could control where you went before, they can switch it out. But it leaves traces.}]
["I paused and thought."]
[me: {Sometimes I don't feel comfortable encouraging people to get involved with this. It was better for me before, when I slept nights and forgot it all. Now I'm bringing you into it.}]
[woman: ("shrugging") "Then thanks for nothing, I guess."]
