realityhandbook [
    date: 29-Sep-2007/13:42+3:00
    category: 'open-letter
    title: "Out of Body Experiences (In?)Validated"
    slug: %validating-out-of-bady-experiences
    tags: []
    old: http://realityhandbook.livejournal.com/46376.html
]
[{Last night I watched an interesting BBC video about four famous contributors to mathematics, all of whom died of suicide or in sanitoriums. It's called "Dangerous Knowledge":}]
[{http://video.google.com/videoplay?docid=-3503877302082311448&q=dangerous+knowledge&total=342&start=0&num=10&so=0&type=search&plindex=0}]
[{It opens talking about <a href="http://en.wikipedia.org/wiki/Georg_Cantor">Georg Cantor</a>, who was given particularly harsh treatment for his theories (now accepted as foundational in mathematics, thus more or less 100% correct as far as we know in 2007). Many of his famous colleagues at the time said his approaches were "a grave disease"... "laughable and wrong"... or called him a "scientific charlatan". The video puts emphasis on how much these attacks from these particular people hurt him, and led him into isolation and self-destruction.}]
[{When the problem you study is only of interest to a small community who can understand it, it is hard on visionaries who find themselves under attack by that group. In my case, I don't know that I have a "group"... but certainly my group is not the New Age movement. They tend to lack education, and they often have extremely bad taste. Even their websites are horrible amalgamations of the worst wallpaper colors, animated GIFs, and grievous application of the <a href="http://www.iheartpapyrus.com" target="_blank">Papyrus font</a>. Though I might find agreement with some of their unique experiences, <i>these are not people I want to spend time getting to know</i>.}]
[{Who do I want to be accepted by? Educated, curious, artistic, scientific people. But as I've mentioned before in terms of my conflict with perspectives like those held by Dawkins and Dennett, there is a tendency for intellectuals to take on an attitude that becomes headstrong and dismissive. What I consider to be my obvious intelligence does not spare me--it is impossible to be respected and have a dissenting viewpoint, when dealing with a conformist group.}]
[{A <a href="http://www.furl.net/forward.jsp?id=26129851">recent study</a> published by some researchers managed to give people a sensation that matches empirical descriptions of "Out of Body Experiences". A lot of bloggers have chosen to write about it, and depending on their biases, they either think it validates the accounts of OBE-havers or invalidates them. I tripped across <a href="http://www.blacksunjournal.com/religion/1032_out-of-body-experiences-debunked_2007.html">a journal</a> in which a converted Atheist quoted a portion of the account including this sentence:}]
[{the studies suggest a scientific explanation for a phenomenon often thought to be a figment of the imagination}]
["And added his own two cents:"]
[{(...) No doubt believers and meditators will come up with some other concocted reason to think science is wrong about this. When will the supernaturalist madness end?}]
["I responded with this:"]
[quote [[{I'm sure many atheists denied that anyone ever experienced an out-of-body experience. Now they might concede "ok, it happened, you weren't making it up... BUT it didn't mean what you thought it meant!" I think many scientists tend to marginalize the significance of that shift. There is a big difference between being right all along, and merely being willing to change your opinion if new evidence comes to light! It's no justification for cruelty or dismissal in the meantime.}] [{So I think you should be more cautious of statements like "when will the supernaturalist madness end?" Some of those you are labeling were the ones who stuck to their guns: they bravely reported the facts of what they saw and experienced in OBEs, and didn't recant merely for fear of being labeled "mad". They gave the data to help motivate the experimentation, and this is a step toward bridging those experiences with existing peer-reviewed research.}] [{Long live the scientific method: cornerstone of intellectual growth and best-known compass of reality. But death to fundamentalism... on both sides of this kind of debate... we have tons still to learn! Who knows what other findings will surprise science and bolster the accounts of some aspects of "supernaturalist" experience?}]]]
[{In truth, I kinda despise religion, and I'm tempted to launch into a <a href="http://youtube.com/watch?v=5Za2k5wA3sk">Edward Norton 25th Hour</a> rant about the various kinds of people I dislike. But I think I see all things as religions; if someone spends all their life in World of Warcraft vs. studying the Torah, I'm not going to say one is obviously better.}]
[{I play Devil's advocate because there's a tiny fraction of people I care about being overlooked and mistreated, myself included. From the outside I don't see how one would tell the difference based on anything other than careful conversation with the individuals in question. So I push for more open-mindedness. But like the four from the video, the fight takes a toll.}]
