realityhandbook [
    date: 17-Oct-2012/12:02+3:00
    category: 'lucid-dream
    title: "The Virus is on the Treasure Ship"
    slug: %virus-on-the-treasure-ship
    tags: [negative helpful conspiracy technology]
]
[{I was at a friend's house that was saturated with a lot of things in boxes. I knew some of these stacks were full of material that had been sorted and needed to be recycled, other things were just random household items and garbage.}]
[{Reflexively I went in to take a shower, but when I did the water just kind of hit the floor. I noticed the shower head was mounted directly over the toilet. Examining the situation in something of a haze, my friend and I realized the bathroom was halfway through some kind of construction transition. It was as if a new toilet had been installed over where the old shower drain was, and a new uninstalled tub was at another location in the bathroom.}]
[me: {Someone has...been in here to do construction. Why would they do that?}]
[{My brain--or at least the one I was occupying--made a connection and had an "A-Ha" moment.}]
[me: {What was your move-out date? When were you supposed to drop off your keys?}]
[friend: "I did drop off my keys."]
[me: {Uh...we got into the apartment last night. Did you drop off all of them?}]
[friend: {Well I gave them a key so they could get in, but I wouldn't be able to get in to get my stuff if I didn't keep the other one.}]
[me: {That's not how it works! Dropping off your keys is supposed to be the signal that everything is out and you are not coming back! It does no good to drop off only *some* of the keys and keep using the apartment. Their concern isn't about when you moved into a new apartment, they just want you out of this one.}]
[{Right around that moment, people were coming to the door and unlocking it to come in.}]
[me: {I bet that's the construction crew. Basically whoever came in and did this work the last couple of days. They didn't realize your stuff was supposed to be gone so they worked around it. It may be easier to cut a deal with them to not tell the office, and give us time to move this stuff.}]
[{My plan was foiled as my friend signaled to me that the obese woman at the door who arrived with the crew was the apartment manager. She apparently knew me somehow. I was standing with only a towel around me from the shower issue earlier...I explained I hadn't noticed the construction and turned the shower on.}]
[{To my surprise, she was understanding--and seemed to blame herself for knowing how dense my friend was, and not being more thorough to check up on his progress. She even offered to get someone with a big truck to take the stuff, and asked if my home could hold anything that wouldn't fit in his. I mentioned I had a truck and helped people move a lot and I'd make sure the stuff was out as quickly as possible.}]
[{A young black girl was moving in, who also showed up.}]
[girl: {I need to be in by Sunday. That's two days from now. I can't get a room anywhere else, all I have are food stamps.}]
[me: {Don't worry, we can get this tied up...I've pulled off tighter moving deadlines than that.}]
[{Then as she was showing the construction crew some things, I stopped and became lucid. Somehow I was shuffling notes on pieces of paper in my hand. I went to go clarify to the apartment manager}]
[me: {I'm not in the process of helping anyone move. I finished a move, but it was different. This friend here is not who I thought, and it's not even a representation of the friend I helped in the other situation.}]
[her: "So what does it mean?"]
[me: {It clearly means I'm not who I've been assuming I am either for the course of this conversation. The person I'm inhabiting may not have a truck. You better send the one you were thinking of.}]
[her: ("smirking") "I was going to anyway."]
[note {I get the feeling that this is someone who was dismissing most of what I'd been saying, assuming I was crazy or retarded.}]
[{Having revealed myself as a body-snatcher, I became tense when one of the workers got wild-eyed and started coming right for me. He stepped forward and thrust his arm up toward my shoulder, and I thought he was going to pinch and attack me. Instead, a piece of what looked like brown packing tape came off as he placed his hand on my shoulder in sort of an odd way...pointing it toward the back wall. I pulled the tape off.}]
[me: {I can do very well without that kick-me sign, thank you!}]
[worker: ("in a trance") {No...you. While you are here, you need to look at that wall. Look where I am pointing.}]
[{I shrugged his arm off and went to look. There were some tacky frames on magazine covers and various posters I did not recognize.}]
[note {In retrospect, one of them *may* have been for a concert or party taking place on a boat. I may be mistaken, but the inkling of that thought will seem more relevant in the context of the experience.}]
[{While the manager was busy I swept the walls of the apartment and looked at the stuff in other rooms, including a strange little one with a work area and art tables. Certain that I'd wake up soon enough, I wandered out the door to look at the world beyond the apartment.}]
[{There was a long river running through whatever this town was, with a knee-high stone wall separating the sidewalk from the banks. Looking down the river, I could see some kind of permanent-installation of what looked like a pirate ship in the middle of the river with a boardwalk out to it from both sides.}]
[{I found the way that people interacted with me to be strange, there were many attractive women who were somehow familiar. There was some open and strange sexuality going on between the people I saw, and at one point I sat on the stone wall to experiment getting involved by fondling a woman's leg. I didn't get slapped, but she seemed to clearly move away preferring to be somewhere else. In the process of moving she bared her body--either conscious of unconscious of how the skirt was showing her nudity underneath.}]
[{Shrugging, I got up and another girl joined me in walking away.}]
[me: {Well, I guess it's not a bad set of rules to have humans be more like animals. You can start by trying to pet them gently. But if they move away from you, you don't push it.}]
[{We wandered and I noticed there were a lot of video-game like pieces of matter in tiles on the sidewalk that could animate and reshape. I scrutinized some of the things, and commented I thought it was cool.}]
[companion: ("scowling") {You actually *like* this? I don't. This place was assembled in a very disturbing way, it's all dead and plastic and fake...so simple that it's grotesque.}]
[me: {Well, we are different. I myself don't like dirt and weeds and earthworms and all that gross stuff. My mind is at home in places that are clean, and where and one can really understand all the parts. And you can still be very creative in such a context, look.}]
[{I somehow managed to dislodge a tile out of the ground. I demonstrated how once I'd removed it, there were controls that let me change the settings. I could alter the shape, material properties, and how it would attach to other tiles near it.}]
[me: {Sure, some people reduce their whole worlds where you get kind of a LEGO-style triviality...that's stifling. But these are decent parts, this place just uses them wrong. Still the point is that I'm disturbed by random splatters which are 'chaotic complex' as opposed to 'controlled complexity'...the latter is more beautiful and soothing to me.}]
[{We wandered into something that was some kind of "welcome center" for this world. I don't remember the entire experience, but it was a sparse room with large bins of what looked like stuffed animals with very large container-shaped mouths.}]
[{A narrated recording explained that the fee to become a citizen was six dollars. If you didn't have six dollars but wanted to make the money you were supposed to collect items from the ground around town and bring them back in the animal's mouth. I thought this was pretty strange, but decided to grab an frog-looking animal from a bin and walked out.}]
[{The frog turned out to not just be a stuffed animal. It was robotic, and you could set it down in an area and tell it to collect for you. Then you would come back and sift through what it had collected and decide if it was the right stuff or not. If it wasn't, you could clear out its mouth and send it again.}]
[{While I puzzled over the robotic controls, the girl came back.}]
[girl: ("angrily") {All right, we've found it. That 'treasure ship' is where they do it...drug and viral contaminants, neuroactive. That's why they put it in the middle of the river; to keep it isolated. The people in power just avoid events on the boat.}]
[me: {They probably didn't even have to drug the populace to make them this painfully retarded. You should see this game you play for the six dollars...it's inane. Anyone who plays it was pretty dumb to begin with. Okay, let me do this one.}]
[{I tossed the frog, and marched back to the "welcome center" in a huff. A man standing inside looked at me confusedly. Since I didn't know if he was affiliated with the center or not, I decided to pump my fist and threaten the speakers that were narrating. I rattled off some various code numbers just to make it interesting.}]
[{The room began to shake and seemingly blast off into the sky.}]
[me: ("sighing") {Building the welcome center as a rocket to blast your enemies into space. I always wonder what good they think this step will do...other than to ensure a stronger punishment?}]
[{The man in the room was giving me a terrified look.}]
[me: {Oh, oops. I probably should have told you to leave before I did this. But look, just trust me. You'll be better off getting out of this hellhole.}]
[{As the room or vessel turned into an upside-down dive, I lost consciousness and awoke in a nice bed in a well-furnished room next to an attractive woman. At first I assumed that I'd woken up as normal, but realized I didn't know who she was and that I was still in a dream.}]
[me: {Well...that's downlevel one, and probably not the last. I'll be doing this a few more times.}]
[woman: {I'm sorry to break it to you, but... you've just collapsed forever into the dimension where you and your perfect lover are trapped in a 4-star hotel room for all of eternity. There's no way out of this one. It's airtight.}]
[note {This seems funny in retrospect, but I didn't laugh at the time. Maybe I should've.}]
[{There was some kind of perceptual zap, to where I was still in bed next to the girl. But we were watching a grid of video screens depicting varied playbacks of deaths we'd experienced. I noticed another man and woman...the man was black but I don't remember the woman, and the scenes followed their deaths too. It wasn't just one time, it was many.}]
[{We found some of the moments of death comical in terms of what we had said, or how egregious the murderers had been.}]
[me: {This is a lot like that scene in the Matrix where Neo is talking to the architect, and all the various responses he's had are being played in parallel. Maybe instead of trying to be all creative, we should just adopt a consistent standard for what we say. I vote for the one where he flips the bird and says 'fuck you!'.}]
[{They laughed and we got up out of the bed to answer the door. I sighed and figured it would be someone coming to attack, but it was a friendly seeming man. He had a strangely shaped vessel of red liquid in his hands, which was open at the top like it could be some kind of punchbowl.}]
[man: {Glad to see the patients are back in one piece...welcome. We're going to be having a meeting at breakfast if you're up for that. But speaking of recovery--you'll be pleased to know the medics cleared you to drink, so do so if you choose.}]
[note {I don't know if he was addressing all four of us with that comment, or just me. Or if he was referring to alcohol, or what was in his bowl, or if that was alcohol or what.}]
[{We walked out into a picturesque world that seemed very idyllic. The group stepped up to a large and architecturally complex building, and standing outside were some goofy-looking men in some unusual-looking but simple uniforms. They were nice but not the military sort, so their uniforms seemed to represent something else.}]
[{The doors were opened for us but I decided not to go in...because I had an inclination to walk down toward the body of water that the building seemed to be straddling. At least one person followed me--who may or may not be the man who had greeted us at the door.}]
[man: {Your restraint and self-control are amazing. To go through everything and still hold back from doing things you *could* do...}]
[me: ("sighing") {I hope one day more people say so. Their weapons are guns and knives and torture. Mine are things like coffee beans in weird patterns outside someone's door. Those really were just coffee beans, folks.}]
[{A woman (who might be the same one I was in bed with earlier) was sitting down and arranging loose rocks.}]
[woman: {This issue of poisons...and the body. It's something that no one there is approaching right. Perhaps the closest perspective is practiced by the 'healers' and those in 'the healing arts', but they are very far behind and not practicing it as a science. At least not the science known to us...at the level we know here.}]
[me: {The operative word in that sentence is 'here'. You realize I truly have no idea where I am, right?}]
[{We wandered up to the building and went inside for breakfast. Before we did, there was someone who was handing out a lot of papers. It was some kind of course schedule for classes we could be taking--some related to software. A bearded guy caught my eye in passing and he didn't seem to recognize me, but I recognized him.}]
[bearded-guy: "Should I know you?"]
[me: "Hmmm... hold on a second."]
[{I thought, and as soon as I recognized who I thought he looked like a third man came up on my left and spoke to him at the same simultaneous moment.}]
[us: "Do you play bridge?"]
[bearded-guy: "Yes."]
[me: "Do you go by Scott here, too?"]
[bearded-guy: "Yes."]
[me: {Then we may have an issue. Or maybe not. It relates to some deeply inconsiderate behavior, me calling you out on it, and you having a very flippant response. The upshot was that you didn't have to worry about lying if it was convenient for your hedonistic agenda vs. consequences for people you don't know well. But one incident does not a character make, and I've written stupid emails too.}]
[{There was some strain as I experienced a rather sudden inability to stay locked on the dream.}]
[me: {But we'll have to come back to it, I'm getting called away now.}]
