realityhandbook [
    date: 5-Sep-2006/12:57+3:00
    category: 'essay
    title: {Will we ever see things as they appear to the others?}
    slug: %will-we-ever-see-things-as-others-see-them
    tags: []
    old: http://realityhandbook.livejournal.com/18390.html
]
[{A common question that those who study consciousness wonder about is that of what it's like to be another animal, such as (say) a bat. A bat is basically blind, so one would suspect that it doesn't experience vision in the way we do. It screeches and uses the echo feedback to model what it needs to know about its environment. But phenomenologically speaking, could a bat have a "visual experience"? In its own head, could it be seeing colors and shapes like we do?}]
[{This gets at those basic boring issues like "If we both look at a red thing, do you see it as blue...but we don't know this because we both call it red?" Odds are we'll never know. Which leads to a question I've been having about laptops and the internet. I've wondered in dreams if those guides who manage to find and deliver messages depend on an ability that's something like a web search.}]
[{I've taken it upon myself lately to do a lot of searching of blogs, based on keywords. I make little comments if I think what they said is interesting and I have something to add, or if I can answer a question that they raised. It's not that important for me to build a relationship with them--I haven't found a lot of people thinking the way I do in particular. Since I only see a little overlap I say just a little and leave. In fact raising the bar a bit by making the comment anonymous seems judicious...I don't care if they trace my IP address or do a strategic web search to find me back. If they do then indeed, I'll happily talk to them.}]
[{Realizing how I feel about this makes me wonder about the attention span of those who would provide guidance in a lucid dream. Do they probe around for someone who has an idea they like and just stop in for a second to say hi, but then disappear because they've got other more local business to attend to?}]
[{I've wondered sometimes about Helen Keller and what a gargantuan mental task it must have been to derive the existence of the outside world from a random smattering of impulses. Who knows what the phenomenology was that she was experiencing while figuring it out? She claimed to not be able to put it into words what that period was like. Is the confusion and disorder I perceive in this world actually my own incompetence at sorting out the bigger pattern? Perhaps once I learn to speak the language of the...uh..."smart language-using things outside my current sphere of perception" they will tell me they've been putting one of my hands under water and making the sign for water in the other. Metaphorically speaking...}]
[{On another note, reaching down into some places on the internet...such as Usenet or archaic blog software...feels a bit like calling down into the past. I've wondered about the relativity of time: if there was a cure for cancer, how long would it take to reach everyone? Let's forget about the cure itself--I mean just the news that it <i>could</i> be cured? There would probably be intentional and unintentional blocks to the dissemination of this information. But off the cuff, how long until everyone on planet Earth knew cancer had been cured? It's an impossible task.}]
